// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/BizListingPremium.tsx": () => import("../components/mockups/BizListingPremium.tsx"),
  "./components/mockups/BizListingStandard.tsx": () => import("../components/mockups/BizListingStandard.tsx")
};
